import Head from "next/head";


import Navbar from "@/components/Navbar/Navbar";
import Main from "@/components/Main/Main";


export default function Home() {
  return (
    <div>
      <Head>
        <title>Badol's portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <Main />
    </div>
  );
}
